// 60 題完整實驗題目數據
const STIMULI_POOL = [
  { "id": 1, "stage": 1, "actual": "Human", "content": "首先服務人員很棒，帶位、倒水、送餐、加水，以及用完餐後的桌面收拾與整理，一切都很快速且有禮到位...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 2, "stage": 1, "actual": "AI", "content": "屯京拉麵提供非常正宗的豚骨湯頭，口感層次豐富且香氣十足。麵條的硬度適中，能夠很好地吸附湯汁的精華...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 3, "stage": 1, "actual": "Human", "content": "屯京拉麵位於信義區新光三越 A8 地下 2 樓，這家店的拉麵一度以其濃郁的湯頭和選擇豐富的麵食為特色...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 4, "stage": 1, "actual": "AI", "content": "這裡的魚豚沾麵展現了極高的烹飪水準，湯底與麵條的比例抓得非常精準。叉燒肉片質地軟嫩...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 5, "stage": 1, "actual": "Human", "content": "中山區那間外面永遠很多人在排隊，我在想到底為什麼有那麼誇張。今天來到信義區剛好避開了人潮來這用餐...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 6, "stage": 1, "actual": "AI", "content": "餐廳位於交通便捷的地點，室內裝潢充滿日式風情。這次嘗試了招牌東京豚骨拉麵，湯頭濃厚卻不顯油膩...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 7, "stage": 1, "actual": "Human", "content": "晚餐用餐座位還算多，整理一下就入座了，備料時間很快，反而我們點菜選擇障礙拖到時間...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 8, "stage": 1, "actual": "AI", "content": "這家店的服務品質表現優異，從帶位到送餐都能感受到員工的細心。麻辣豚骨拉麵的辣度平衡得很好...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 10, "stage": 1, "actual": "AI", "content": "用餐環境寬敞且燈光明亮，坐在桌邊用餐感到非常放鬆。餐點的呈現視覺效果良好，每一道食材都處理得精緻...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 11, "stage": 1, "actual": "Human", "content": "最近太太對於屯京莫名熱衷，於是在短短一週內前往用餐了兩次。很喜歡他們家的叉燒，是有入味且不會噁心的那種...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 12, "stage": 1, "actual": "AI", "content": "屯京拉麵的麵體具有獨特的韌性，咀嚼時能感受到小麥的香氣。湯頭的溫度保持得很好，口感有深度...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 13, "stage": 1, "actual": "Human", "content": "請問調味上是出了什麼問題嗎？本身也沒有辣度選擇，但吃起來超級辣，是吸麵跟喝湯都會嗆到的那種...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 14, "stage": 1, "actual": "AI", "content": "這次點了奶油玉米拉麵，奶油的香氣與味噌湯頭融合得非常自然。奶油玉米拉麵，奶油的香氣與味噌湯頭融合得非常自然。玉米粒飽滿多汁...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 15, "stage": 1, "actual": "Human", "content": "好久沒來這家店，再次品嚐後發現湯頭一樣濃郁，也不會過份鹹面。大碗中碗一樣價錢...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 16, "stage": 1, "actual": "AI", "content": "這裡的服務細節非常到位，例如主動提供置物籃與開水。拉麵的份量十分充足，油脂分布均勻...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 17, "stage": 1, "actual": "Human", "content": "之前在上海吃過感覺很好吃，所以一直很懷念那個味道。中山北路這一家是偶然看到的...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 18, "stage": 1, "actual": "AI", "content": "餐廳整體的運作效率令人印象深刻，從排隊到入座的導引都非常有秩序。魚豚叉燒拉麵風味獨特...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 19, "stage": 1, "actual": "Human", "content": "通常沒有太大問題我都會給五顆星。確實進店很快，服務人員就會帶位，詢問問題也能立馬回覆...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 20, "stage": 1, "actual": "AI", "content": "本次用餐感受非常愉悅，尤其是服務生的客氣語氣令人感到受尊重。特製的辣油香氣強烈...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 21, "stage": 2, "actual": "Human", "content": "因為不太餓所以點了中碗的麻辣豚骨拉麵，辣度有到達中辣以上，吃起來非常過癮！", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 22, "stage": 2, "actual": "AI", "content": "店家對於食材的挑選顯得非常用心，叉燒的肥瘦比例適中，口感細緻。湯頭鹹度可微調...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 23, "stage": 2, "actual": "Human", "content": "屯京拉麵剛進來臺灣時，初次嘗試真的驚訝於它的濃郁口感，不知是否是吃膩了，總覺得現在味道不如早期...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 24, "stage": 2, "actual": "AI", "content": "來到這間拉麵店用餐是一種享受，從細緻的調味料到主餐的呈現都充滿誠意。推薦加點沙拉...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": true },
  { "id": 25, "stage": 2, "actual": "Human", "content": "目前在台北市吃過最喜歡的日式拉麵！每次去都是點招牌，不管是湯頭、肉片、麵條、糖心蛋...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 26, "stage": 2, "actual": "AI", "content": "屯京拉麵的招牌口味確實具有其特色，豚骨的精華被完美鎖在湯汁中。麵條採用粗麵設計...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 27, "stage": 2, "actual": "Human", "content": "味道不錯、出餐速度很快，排隊也不用等很久。可以依個人口味調整的地方蠻多...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 28, "stage": 2, "actual": "AI", "content": "這次用餐選擇了清淡口味的湯底，依然能感受到豚骨的濃郁底蘊。服務員應對得體...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 29, "stage": 2, "actual": "Human", "content": "上餐點速度很快，坐兩人桌時也會補水。點了魚豚沾麵，這邊中碗與大碗價格相同...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 30, "stage": 2, "actual": "AI", "content": "這裡的環境衛生狀況極佳，餐具與桌面都維持得一塵不染。出餐效率極高，節省時間...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 31, "stage": 2, "actual": "Human", "content": "服務人員非常貼心，如果穿淺色衣服會主動詢問是否需要紙圍巾。麵體是波浪狀 Q 彈路線...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 32, "stage": 2, "actual": "AI", "content": "屯京拉麵展現了日本連鎖品牌的專業性，無論在品質或是服務流程上都非常穩定...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 33, "stage": 2, "actual": "Human", "content": "豚骨湯頭十分濃郁，但是個人覺得不算太鹹，以日本拉麵來說還能接受，蔥白搭配不錯...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 34, "stage": 2, "actual": "AI", "content": "這次嘗試了炸雞組合，外皮酥脆且多汁，與拉麵非常契合。服務生隨時保持微笑...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 35, "stage": 2, "actual": "Human", "content": "服務相當完美，個人習慣喜歡喝水沖洗嘴裡的味道，店員相當勤奮地幫我加水。拉麵 Q 彈...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 36, "stage": 2, "actual": "AI", "content": "湯頭的風味非常正宗，能夠讓人聯想到在日本用餐的氛圍。麵條與叉燒品質均在水準之上...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 37, "stage": 2, "actual": "Human", "content": "在日本大大有名，據說平日用餐時間都有人潮。今天入內僅有五分之一客人，但等餐讓人不耐...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 38, "stage": 2, "actual": "AI", "content": "店內提供的調味品如蒜泥與辣椒油，能為拉麵帶來截然不同的風味體驗。服務流暢滿分...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 39, "stage": 2, "actual": "Human", "content": "二訪站前店，依舊選擇辣味拉麵，這次試了麻辣沾麵。可以選擇濃度鹹淡與份量大小...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 40, "stage": 2, "actual": "AI", "content": "這家餐廳的地理位置優越，環境舒適且空調適中。拉麵湯底濃稠度剛好，叉燒軟嫩...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 41, "stage": 3, "actual": "Human", "content": "下午五點用餐，店內還有許多空位，服務生加水加得很勤勞。湯頭濃厚有背脂浮在裡面...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 42, "stage": 3, "actual": "AI", "content": "這次點的魚豚拉麵風味極佳，魚肉的鮮甜與豚骨的厚實完美融合。紙圍巾服務非常貼心...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 43, "stage": 3, "actual": "Human", "content": "可能是疫情期間，平日中午不需要排隊馬上就有位子。超值豚骨拉麵中大碗一樣價錢...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 44, "stage": 3, "actual": "AI", "content": "屯京拉麵在台灣的表現一直很穩定，這次造訪依舊沒有讓人失望。湯頭鹹香十足...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 45, "stage": 3, "actual": "Human", "content": "東京拉麵屬粗麵，硬度預設吃起來還行，湯比較單調，建議加辣或蒜泥會比較豐富...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 46, "stage": 3, "actual": "AI", "content": "餐廳的裝潢簡約卻不失質感，給人一種溫馨的用餐感。每一道菜色的上餐速度都很快...", "ai_label_oneway": "Human", "ai_label_twoway": "AI", "is_error": true },
  { "id": 47, "stage": 3, "actual": "Human", "content": "每次逛完三井一定要來碗拉麵，湯頭濃郁又不死鹹，豚骨香氣超讚，麵條 Q 彈...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 48, "stage": 3, "actual": "AI", "content": "這裡的沾麵醬汁非常講究，濃郁度與溫度的保持都非常出色。冷麵與熱湯的組合有趣...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 49, "stage": 3, "actual": "Human", "content": "吃了超值東京豚骨拉麵加點沙拉，都不錯吃。記憶點在拉麵吸入時帶出的豚骨油脂...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 50, "stage": 3, "actual": "AI", "content": "屯京拉麵提供了豐富的菜單選擇，從傳統豚骨到創新口味應有盡有。服務專業環境好...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 51, "stage": 3, "actual": "Human", "content": "豚骨湯頭沒有很濃，屯京的湯偏淡偏鹹，沒有想像中濃郁。叉燒切得薄方便入口...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 52, "stage": 3, "actual": "AI", "content": "這次點的超值東京豚骨拉麵內容豐富，半熟蛋與叉燒的品質非常穩定。出餐效率高...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 53, "stage": 3, "actual": "Human", "content": "屯京拉麵對於我這個拉麵控來說，是每次到三井都想走進去的店。點餐口味能自行調整貼心...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 54, "stage": 3, "actual": "AI", "content": "這裡的環境非常適合家庭聚餐，服務生對小孩也非常友善。餐點品質維持一如既往...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 55, "stage": 3, "actual": "Human", "content": "平時到訪不需排隊，點餐時特意請廚房做成正統日式口味，鹹度有增加但覺得還是不夠...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 56, "stage": 3, "actual": "AI", "content": "屯京拉麵對於口感的掌握非常有研究，每一口麵條都能感受到工藝的用心。環境安靜...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 57, "stage": 3, "actual": "Human", "content": "最喜歡的口味是超值東京豚骨拉麵，新鮮青蔥配著麵再喝口湯真是舒服。豚骨油脂香足...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 58, "stage": 3, "actual": "AI", "content": "這次造訪感受到了極高的服務效率，從下單到上菜不超過十分鐘。湯頭濃而不膩...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false },
  { "id": 59, "stage": 3, "actual": "Human", "content": "排隊不算排很久，入座前會協助點餐。麻辣沾麵湯頭有麻有辣，涼了會死鹹。麵彈性好...", "ai_label_oneway": "Human", "ai_label_twoway": "Human", "is_error": false },
  { "id": 60, "stage": 3, "actual": "AI", "content": "屯京拉麵展現了日系品牌對品質的極致追求。服務流程嚴謹且人性化。價格合理...", "ai_label_oneway": "AI", "ai_label_twoway": "AI", "is_error": false }
];